spring:
  application:
    name: Post

  datasource:
    url: 'jdbc:mysql://localhost:3306/postdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8'
    username: root
    password: oijwef098234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update           # create / create-drop / update / validate / none
    show-sql: true               # SQL 출력
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

# SQL 바인딩 값까지 보고 싶으면(선택)
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
